name: Run Pytest Tests

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image
    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Check out the code from your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set Python version (you can choose the version you need)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt (if you have one)

      - name: Run tests with pytest
        run: |
          pytest  # Run the pytest tests
